### ISSUE TITLE
WebAPI Port 4317 should be configurable by env var

### ISSUE THREAD

**Issue by DoubleTK** [OddDotNet/OddDotNet#2]
WebAPI needs to be set up to allow configuration of the port number being used. This configuration should be handled by environment variable so that it is configurable both as a project and as a container.

**Comment by handro1** [comment]
You can change the port used by the application at startup by using `ASPNETCORE_`, `DOTNET_`, or "no prefix" to specify the values:

`HTTP_PORTS` (and `HTTPS_PORTS`)
`ASPNETCORE_HTTP_PORTS` (and `ASPNETCORE_HTTPS_PORTS`)

**Comment by DoubleTK** [comment]
You're right. We'll just use these already defined env vars to configure. Closing!
